### ISSUE TITLE
Open CodeQueryMenu error.

### ISSUE THREAD

**Issue by xdidi3r** [devjoe/vim-codequery#14]
![5b7849e3-ae09-4017-81e1-4d5f3942a725](https://cloud.githubusercontent.com/assets/23443899/23513688/e1b27ac8-ff9f-11e6-90e2-017a6c8bf6a1.png)

**Comment by devjoe** [comment]
Hi @xdidi3r,
  
(sorry for late response)
  
You will need to install [Unite](https://github.com/Shougo/unite.vim) to use the menu.
