### ISSUE TITLE
Use go back function, like ctags ?

### ISSUE THREAD

**Issue by chenweiy** [devjoe/vim-codequery#15]
I like this project. But i have a problem.
Can vim-codequery use go back function ,like ctags use ' Ctrl+t' to go back in tag stack?

**Comment by devjoe** [comment]
Hi @chianwei123,
  
(sorry for late response)
  
Could `Ctrl+o` help you?
By the way, i frequently use `:cnext` and `:cprevious` to jump between quickfix items.
