### ISSUE TITLE
The quickfix window opens under the Nerdtree window or Tagbar window. It should always be below the main window.

### ISSUE THREAD

**Issue by tainzhi** [devjoe/vim-codequery#17]
Sir,
I am puzzeled with this becauce the quickfix window doesn't open below the main window. I have searched the [site](http://stackoverflow.com/questions/37309122/vim-quickfix-list-manipulate-location), end with no good solution to it.

Before I have installed a plug [AsyncRun](https://github.com/skywind3000/asyncrun.vim/search?utf8=%E2%9C%93&q=quickfix_toggle&type=), it perfectly solves the problem and makes the quickfix window open below the main window.

I will be grateful from my heart if you can reply to me.

Thanks.

**Comment by devjoe** [comment]
Hi @fq-qiu, 
  
Sorry for late response.  😥

Your problem can be solved by adding the following snippet to your `.vimrc`.

```vim
augroup DragQuickfixWindowDown
    autocmd!
    autocmd FileType qf wincmd J
augroup end
```
  

From now on, whenever you call `:copen` liked commands to open quickfix window, you will have a global quickfix window on the bottom down. I hope this snippet could help you.

**Comment by tainzhi** [comment]
Hi @devjoe 
Thanks for your replay and kind help.
I copy the comand, but it results to a new problem
```bash
Error detected while processing FileType Auto commands for "qf":
E788: Not allowed to edit another buffer now
```
That is, it couldn't works well under my vim setting environment. I read the vim help document and google  the error for a few hours with no better explanations. Although it doesn't solve the problem, it gives me some insight into `wincmd J` and `qf`. Thanks for your kindly replay.
Happy everty day, happy coding.
