### ISSUE TITLE
Please add info on how to install without VIM Plugin Manager.

### ISSUE THREAD

**Issue by gpaulsen** [devjoe/vim-codequery#18]
Please add info to the Readme on how to install vim-codequery for vim8 without using a vim plugin manager (or links to the plugin manager if that's REALLY the preferred way).

Thanks,
I can't wait to try CodeQuery.

**Comment by devjoe** [comment]
Hi @gpaulsen, 

Added in 020a8a83457b2a60c66ba4e9cd83897d509a120c.
Thanks for your suggestion.

**Comment by gpaulsen** [comment]
Great!  Thanks so much,  Will try it out tonight! :)
