### ISSUE TITLE
Not Supported Filetype:  

### ISSUE THREAD

**Issue by upadhayaykapil** [devjoe/vim-codequery#28]
1. Ubuntu 18.04, open gvim in the root directory of project
2. :CodeQueryMakeDB python
3. :CodeQuery Definition <any_symbol>

Always displays Not Supported Filetype:

**Comment by devjoe** [comment]
Did you run `CodeQuery Definition <any_symbol>` in a Python file?
Say you have
* `main.py`
* `main.js`
* `readme.md`

If you run `CodeQuery Definition <any_symbol>` from a Python file, the plugin will look up your Python index database. On the other hand, if you run from a JavaScript file, it will look up the JavaScript index database. So, if you run this command while editing a Markdown file, the plugin can not know how to look up the index database.

**Comment by upadhayaykapil** [comment]
My project has lots of python files. So far, I was using gvim along with cscope and ctags. I wished to use CodeQuery and went through the online documentation, setup the python.db. And when I try to use CodeQuery in my gvim, I always get this error.

Just in case a little more information if it may help you, I also installed codequery binary on my machine and that works perfectly fine. I mean, if i create a dedicated codequery.db and open it up from codequery binary, it works. It only that I want to use it through vim.

**Comment by upadhayaykapil** [comment]
devjoe, I just cd to my project directory. lets say, this is my project structure:
/home/kapil/myproject/src/server/lots_of_python_files
/home/kapil/myproject/src/other_server/lots_of_c_files

Here is what I did:
1. cd /home/kapil/myproject/src
2. open vim 
3. Inside vim,  : CodeQueryMakeDB python
4. then,  : CodeQueryMoveDBToGitDir python
5. Now, when I do any of codeQuery command, I hit this issue.

**Comment by upadhayaykapil** [comment]
Thanks, devjoe your comment made sense. 
It works now, only thing is that you need to open a python file first and then every thing falls in place.  I just opened vim in project root directory and then searched for the symbol(as i never remember the file only the function name), where it issued me error. I guess as a user its normal to open up in this way and the error is non-intuitive.

Thanks Devjoe for your support.
